Algoritmo "Maior ou menor de idade"
// Disciplina   : [Algoritmos e Programação Estruturada]
// Professor   : Vanessa Matias Leite
// Descrição   : Programa diz se a pessoa é maior ou menor de idade
// Autor(a)    : Fernando Henrique Panini
// Data atual  : 19/10/2022
Var
idade: inteiro


Inicio
      escreva("Digite a idade: ")
      leia(idade)

      se(idade>=18)entao
      escreva("maior de idade")
      senao
      escreva("menor de idade")
      fimse


Fimalgoritmo